#!/bin/sh

# Start programmer for graphische miljøer
#backweb &			# Sett bakgrunnen
./.fehbg
unclutter &			# Gøym musa etter ei stund
dunst &				# Meldingsbokar
compton -bfc			# Gennomsiktighet
sxhkd &				# Enkel X Heiteknapper Demon
[ "$WM" = "dwm" ]   dwmbar &	# dwm bar
xkbutil set "$(cat $XDG_CONFIG_HOME/keymaps/current-layout)" &
#minuttvarsel &

#while :; do
"$WM"
#done
