#!/bin/sh

# Generelle
super + Return
	$TERMINAL

super + Tab
	rofi -show run -theme sidetab

super + space
	xkbutil toggle && lemonblocks-reload keymap

# PageUp og PageDown
super + {_,shift +} {Next,Prior}
	amixer sset Master {10,20}%{-,+} && lemonblocks-reload volume

super + {Home,End}
	amixer sset Master {100,50}% && lemonblocks-reload volume

super + w
	dugrep mkv,mp4,avi mpv

super + e
	$TERMINAL -e ranger

super + r
	gnumeric "$HOME/git/regneskap/regneskap-2020.ods"

super + control + r
	$HOME/.local/bin/reloadwm

super + y
	mpv "$(xclip -out)"
	#youtube-dl "$(xclip -out)" -o - | vlc - {_,--sout "#chromecast" --sout-chromecast-ip="192.168.10.178"}

super + shift + y
	surf "https://www.yr.no/stad/Noreg/Vestfold_og_Telemark/Larvik/Larvik/time_for_time.html"

super + p
	thunderbird

super + shift + i
	$TERMINAL -e htop

super + o
	wiktionaire uib

super + a
	$TERMINAL -e pulsemixer

super + s
	urxvt -e ssh riq@192.168.10.173

# Swap the current node and the biggest node
super + g
	gnome-calculator

super + h
	surf "https://www.hurtigruten.no/kart/?shipCode=MS"

super + l
	i3lock -ei "$XDG_CONFIG_HOME/lock-img.png" -p win

#super + x
#	[ "$(echo -e 'Nei\nJa' | rofi -dmenu -p 'Vil du logge av?' -lines 2)" = "Ja" ] && bspc quit

super + shift + x
	[ "$(echo -e 'Nei\nJa' | rofi -dmenu -p 'Vil du slå av PC-en?' -lines 2)" = "Ja" ] && $TERMINAL -e "sudo shutdown -h now"

super + c
	_file="$(du -a $XDG_CONFIG_HOME | cut -f2 | rofi -dmenu -p "")" && [ "$_file" != "" ] && code "$_file"

super + v
	wiktionaire

super + n
	dugrep pdf zathura

super + shift + n
	dugrep groff code && sleep 1s && lemonblocks-reload volume

super + {_,shift +} m
	amixer sset Master {toggle,mute} && lemonblocks-reload volume

# Screenshots and recording
{_,shift +} Print
	cd $HOME/Bilder/skjermdumper && scrot -z{_,u} && cd

super + {_,shift +} Print
	dmenurecord {_,kill}

#F keys
super + {_,shift +} F5
	$HOME/.local/bin/wifi-select {_,-n}

# XF86 Keys
XF86AudioMute
	amixer sset Master toggle && lemonblocks-reload volume

XF86Audio{Lower,Raise}Volume
	amixer sset Master {10,20}%{-,+} && lemonblocks-reload volume

XF86AudioNext
	cmus-remote --next

XF86AudioPlay
	cmus-remote --pause

XF86AudioPrev
	cmus-remote --prev

XF86AudioStop
	cmus-remote --stop

XF86Sleep
	lockscreen
