#!/bin/sh

# Generelle
super + {_,shift +} Return
	$TERMINAL {_,-e tmux}

super + Tab
	rofi -show run -theme sidetab

super + space
	xkbutil toggle && lemonblocks-reload keymap

super + control + Delete
	i3lock -ei "$XDG_CONFIG_HOME/lock-img.png" -p win && systemctl suspend

# PageUp og PageDown
super + {Next,Prior}
	amixer sset Master 5%{-,+} && lemonblocks-reload volume

super + {Home,End}
	amixer sset Master {100,50}% && lemonblocks-reload volume

# Bokstavkombinasjonssnarveier
super + w
	dugrep mkv,mp4,avi mpv

super + e
	$TERMINAL -e ranger

super + r
	gnumeric "$HOME/git/regneskap/regneskap-2020.ods"

super + control + r
	$HOME/.local/bin/reloadwm

#super + t
#	[ "$WM" = "i3" ] && i3-msg split toggle

super + y
	notify-send "Åpner mpv..." && \
	mpv "$(xclip -out)" \
		--ytdl-raw-options=format="best[height<=480]" || \
	notify-send "Åpning av video feilet!"

super + shift + y
	notify-send "Åpner mpv..." && \
	mpv "$(xclip -out)" \
		--no-video --player-operation-mode=pseudo-gui || \
	notify-send "Åpning av video feilet!"

# super + shift + y
# 	surf "https://www.yr.no/stad/Noreg/Vestfold_og_Telemark/Larvik/Larvik/time_for_time.html"

super + p
	thunderbird

super + shift + i
	$TERMINAL -e htop

super + o
	wiktionaire uib

super + a
	$TERMINAL -e pulsemixer

super + s
	echo "rk@cassettian.space\nriq@192.168.1.4" | rofi -dmenu | xargs urxvt -e ssh

super + f
	bspc desktop -l next

super + shift + f
	bspc node focused -t floating || bspc node focused -t tiled

super + h
	surf "https://www.hurtigruten.no/kart/?shipCode=MS"

super + k
	gnome-calculator

super + shift + k
	$TERMINAL -e calcurse

super + l
	i3lock -ei "$XDG_CONFIG_HOME/lock-img.png" -p win

super + shift + x
	[ "$(echo -e 'Nei\nJa' | rofi -dmenu -p 'Vil du slå av PC-en?' -lines 2)" = "Ja" ] && $TERMINAL -e "sudo shutdown -h now"

super + c
	_file="$(du -a $XDG_CONFIG_HOME | cut -f2 | rofi -dmenu -p "")" && [ "$_file" != "" ] && code "$_file"

super + {_,shift +} v
	wiktionaire {_,uib}

super + n
	dugrep pdf zathura

super + shift + n
	dugrep groff code

super + {_,shift +} m
	amixer sset Master {toggle,mute} && lemonblocks-reload volume

# Screenshots and recording
{_,shift +} Print
	cd $HOME/Bilder/skjermdumper && scrot -z{_,u} && cd

super + {_,shift +} Print
	dmenurecord {_,kill}

#F keys
super + {_,shift +} F5
	$HOME/.local/bin/wifi-select {_,-n}

# XF86 Keys
XF86AudioMute
	amixer sset Master toggle && lemonblocks-reload volume

XF86Audio{Lower,Raise}Volume
	amixer sset Master 5%{-,+} && lemonblocks-reload volume

XF86AudioNext
	cmus-remote --next

XF86AudioPlay
	cmus-remote --pause

XF86AudioPrev
	cmus-remote --prev

XF86AudioStop
	cmus-remote --stop

XF86Sleep
	lockscreen

