#!/bin/sh

# bspwm focus the node in the given direction
super + {_,shift +} {Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

super + control + {Left,Right}
	bspc desktop -f {prev,next}.local && lemonblocks-reload desktops

super + {_,shift +} {1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}' && \
	lemonblocks-reload desktops

# bspwm expand a window by moving one of its side outward
super + alt + Right
	bspc node -z right 20 0

super + alt + Left
	bspc node -z right -20 0

super + q
	bspc node -c;

super + x
	[ "$(echo -e 'Nei\nJa' | rofi -dmenu -p 'Vil du logge av?' -lines 2)" = "Ja" ] && bspc quit
